name: Terraform CD

on:
  pull_request:
    types: [closed]

jobs:
  apply-terraform:
    if: github.event.pull_request.merged == true
    name: 'Apply terraform infra'
    runs-on: ubuntu-latest
    environment: development

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="resource_group_name=${{ secrets.TF_BACKEND_CONFIG_RG_NAME }}" -backend-config="storage_account_name=${{ secrets.TF_BACKEND_CONFIG_SA_NAME }}" -backend-config="container_name=${{ secrets.TF_BACKEND_CONFIG_CONTAINER_NAME }}" -backend-config="key=${{ secrets.TF_BACKEND_CONFIG_FILE_KEY }}"
    
    - name: Terraform Plan
      run: terraform plan -var-file=./environments/dev/dev.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=./environments/dev/dev.tfvars -auto-approve